micronaut.application.name=aluguel-carros
micronaut.server.port=8080

# Configuração do Banco H2 em memória
datasources.default.url=jdbc:h2:mem:locadoraDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
datasources.default.driverClassName=org.h2.Driver
datasources.default.username=sa
datasources.default.password=

# Configuração do JPA/Hibernate
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true

# Configuração do Thymeleaf
micronaut.views.thymeleaf.enabled=true
micronaut.views.thymeleaf.cache=false